import data from '../data/countries.json';

export const REGIONS = ['Africa', 'Americas', 'Asia', 'Europe', 'Oceania'] as const;
export type Region = (typeof REGIONS)[number];

export interface Country {
  /** ISO 3166-1 alpha-2, lowercase; also the flag-icons file name. */
  code: string;
  /** ISO 3166-1 numeric; matches world-atlas feature ids. */
  numeric: string;
  name: string;
  capital: string;
  region: Region;
  subregion: string;
  /** False for countries too small for the 1:50m world map (Tuvalu). */
  inMap: boolean;
}

/** The 194 sovereign states, generated by scripts/build-countries.mjs. */
export const COUNTRIES = data as Country[];

export type RegionFilter = Region | 'World';
export const REGION_FILTERS: readonly RegionFilter[] = ['World', ...REGIONS];

export function regionSlug(region: RegionFilter): string {
  return region.toLowerCase();
}

export function parseRegion(slug: string | undefined): RegionFilter {
  return REGION_FILTERS.find((r) => regionSlug(r) === slug) ?? 'World';
}
